mexigrow/catalog/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^login-user/$', views.login_buildout, name='login-user'),
    re_path(r'^reg/$', views.reg, name='reg'),
    re_path(r'^logout-user/$', views.logout_buildout, name='logout-user'),
    re_path(r'^bid/$', views.bid, name='bid'),
    
    
    re_path(r'^proyects/$', views.ProyectListView.as_view(), name='proyects'),
    re_path(r'^proyect/(?P<pk>\d+)$', views.ProyectDetailView.as_view(), name='proyect-detail'),
    
    re_path(r'^myinvestments/$', views.OwnedProyectsByUserListView.as_view(), name='my-investments'),
    re_path(r'^myinvestment/(?P<pk>\d+)$', views.OwnedProyectsByUserDetailView.as_view(), name='my-investment'),
    
    re_path(r'^proyect/create/$', views.ProyectCreate.as_view(), name='proyect_create'),
    re_path(r'^proyect/(?P<pk>\d+)/update/$', views.ProyectUpdate.as_view(), name='proyect_update'),
    re_path(r'^proyect/(?P<pk>\d+)/delete/$', views.ProyectDelete.as_view(), name='proyect_delete'),
    
    re_path(r'^investment/create/$', views.ProyectInstanceCreate.as_view(), name='proyectinstance_create'),
    re_path(r'^investment/(?P<pk>\d+)/update/$', views.ProyectInstanceUpdate.as_view(), name='proyectinstance_update'),
    re_path(r'^investment/(?P<pk>\d+)/delete/$', views.ProyectInstanceDelete.as_view(), name='proyectinstance_delete'),
]

mexigrow/mexigrow/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('catalog/', include('catalog.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mexigrow/catalog/models.py
from django.db import models
from django.urls import reverse

import uuid
from django.contrib.auth.models import User
from datetime import date
# Create your models here.
class Proyect(models.Model):
    title = models.CharField(max_length=200, help_text='Ingresa el título del proyecto.')
    summary = models.TextField(default="",max_length=1000, help_text='Ingresa una descripción de la inversión.')
    mini_summary = models.TextField(default="",max_length=50, help_text='Ingresa una descripción breve de la inversión. No más de 50 carácteres.')
    company = models.CharField(max_length=200, help_text='Ingresa el nombre de la compañía que dirige el proyecto.')
    date_published = models.DateField(null=True, blank=True, help_text='Fecha de publicación.')
    interest_rate = models.DecimalField(default=0, max_digits=10, decimal_places=8)

    # add image 
    def __str__(self):
        return f'{self.title}, {self.company}'

    def get_absolute_url(self):
        return reverse('proyect-detail', args=[str(self.id)])
    class Meta:
        permissions = (("can_add_proyect", "Puede añadir proyecto"),)
    
class ProyectInstance(models.Model):
    proyect = models.ForeignKey('Proyect', on_delete=models.SET_NULL, null=True)
    date_acquired = models.DateField(null=True, blank=True, help_text='Fecha de unión al proyecto')
    date_of_end_contract = models.DateField(null=True, blank=True, help_text='Fecha de fin de unión al proyecto')
    investment = models.DecimalField(default=0, max_digits=19, decimal_places=10)
    investor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    rate_time = models.IntegerField(default=0)
    
    # add image 
    @property
    def proyect_participation_ended(self):
        if self.date_of_end_contract and date.today() > self.date_of_end_contract:
            return True
        return False
    
    def get_absolute_url(self):
        return reverse('my-investment', args=[str(self.id)])
    
    def __str__(self):
        return '%s (%s)' % (self.investor, self.proyect.title)
    class Meta:
        permissions = (("can_add_instance_proyect", "Puede añadir inversión"),)
    
    

mexigrow/catalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username', 'email', 'first_name', 'last_name', 'password1', 'password2')
        

mexigrow/catalog/views.py
from django.shortcuts import render, redirect
from django.views import generic

from .models import Proyect, ProyectInstance

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import RegistrationForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

def reg(request):
    if request.method=="POST":
        user_form=RegistrationForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            return HttpResponse("<h1>Registration succesfully</h1>")
    else:
        user_form=RegistrationForm()
    return render(request, "registration.html", {"user_form": user_form})

from django.views.decorators.csrf import csrf_protect

from django.core.mail import send_mail
from django.conf import settings


def bid(request):
    if request.method =='POST':
        name=request.POST['name']
        proyect=request.POST['proyect']
        email=request.POST['email']
        date_acq=request.POST['date_acq']
        end_cont=request.POST['end_cont']
        amount=request.POST['amount']
        message = name + " se interesa en " + proyect + ". Su email es: " + email + ". Inicio: " + date_acq + ". Fin: " + end_cont + ". Monto: " + amount
        email_from=settings.EMAIL_HOST_USER,
        send_mail(
            'Puja',
            message,
            email_from,
            [email],
            
        
        )
        return render(request, 'index.html')
    return render(request, 'bid.html')
   
@csrf_protect
def login_buildout(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        user=authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('index'))
            else:
                return HttpResponse("<h1> Disable account </h1>")
        else:
            return HttpResponse("<h1> Invalid login </h1>")
    else:
        pass
    return render(request, "login.html")


@login_required
def logout_buildout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def index(request):
    return render (request, 'index.html' )



class ProyectListView(generic.ListView):
    model = Proyect
    queryset = Proyect.objects.all()
    paginate_by = 10

class ProyectDetailView(generic.DetailView):
    model = Proyect

from django.contrib.auth.mixins import LoginRequiredMixin

class OwnedProyectsByUserListView(LoginRequiredMixin,generic.ListView):
    model = ProyectInstance
    template_name ='catalog/proyectinstance_list_owned_user.html'
    paginate_by = 10

    def get_queryset(self):
        return ProyectInstance.objects.filter(investor=self.request.user).order_by('date_acquired')
    
class OwnedProyectsByUserDetailView(LoginRequiredMixin,generic.DetailView):
    model = ProyectInstance
    template_name ='catalog/proyectinstance_detail_owned_user.html'
    paginate_by = 10
    context_object_name = 'pi'
    
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Proyect

from django.contrib.auth.mixins import PermissionRequiredMixin

class ProyectCreate(PermissionRequiredMixin, CreateView):
    model = Proyect
    fields = ['title','summary','mini_summary','company', 'date_published', 'expected_interest_rate']
    initial={'date_published':'01/01/2024'}
    permission_required = 'catalog.can_add_proyects'


class ProyectUpdate(PermissionRequiredMixin, UpdateView):
    model = Proyect
    fields = ['title','summary','mini_summary','company', 'date_published', 'expected_interest_rate']
    permission_required = 'catalog.can_add_proyects'

class ProyectDelete(PermissionRequiredMixin, DeleteView):
    model = Proyect
    success_url = reverse_lazy('proyects')
    permission_required = 'catalog.can_add_proyects'



class ProyectInstanceCreate(PermissionRequiredMixin, CreateView):
    model = ProyectInstance
    fields = ['id','proyect','date_acquired','date_of_end_contract', 'investment', 'investor']
    initial={'date_acquired':'01/01/2024', 'date_of_end_contract': '01/01/2024'}
    permission_required = 'catalog.can_add_instance_proyect'

class ProyectInstanceUpdate(PermissionRequiredMixin, UpdateView):
    model = ProyectInstance
    fields = ['id','proyect','date_acquired','date_of_end_contract', 'investment', 'investor']
    permission_required = 'catalog.can_add_instance_proyect'

class ProyectInstanceDelete(PermissionRequiredMixin, DeleteView):
    model = ProyectInstance
    success_url = reverse_lazy('proyects')
    permission_required = 'catalog.can_add_instance_proyect'

mexigrow/catalog/templates/catalog/e_mail.html
{% extends "base_generic.html" %}

{% block content %}

<form action="{% url 'contact' %}" method="post">
    {% csrf_token %}
    <span>Contacto</span>
    <div>
        <input type="text" name="name" placeholder="nombre">
    </div>
    <div>
        <input type="text" name="email" placeholder="nombre">
    </div>
    <div>
        <input type="text" name="subject" placeholder="nombre">
    </div>
    <div>
        <input type="text" name="message" placeholder="nombre">
    </div>

</form>
{% endblock %}

mexigrow/catalog/templates/catalog/email_template.html
{{ message }}

{{ name }}

{{ email }}

mexigrow/catalog/templates/catalog/proyect_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Eleminar proyecto</h1>

<p>Seguro quieres eliminar a este proyecto: {{ proyect }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Sí" />
</form>

{% endblock %}

mexigrow/catalog/templates/catalog/proyect_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Nombre del proyecto: {{ proyect.title }} </h1>
<hl>
<div>
    <h5>Día en que se publicó: {{ proyect.date_published }}</h5>
    <h5>Compañía encargada del proyecto: {{ proyect.company }}</h4>
    <h4>¿De qué trata el proyecto?: {{ proyect.summary }}</h4>
</div>
{% endblock %}

mexigrow/catalog/templates/catalog/proyect_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

mexigrow/catalog/templates/catalog/proyect_list.html
{% extends "base_generic.html" %}

{% block content %}
  <div >

  <h1 class="pro-li">Proyectos disponibles actualmente</h1>
  {% if proyect_list %}
      {% for proyect in proyect_list %}
      <div class="proyect">
        <a href="{{ proyect.get_absolute_url }}">{{ proyect.title }} </a>
        <h4>({{proyect.company}})</h4>
        <h4>{{ proyect.mini_summary }}</h3>
      </div>
      {% endfor %}


      
      
  {% else %}
    <p>No hay proyectos de momento. Vuelve más tarde.</p>
  {% endif %}
  </div>
{% endblock %}

mexigrow/catalog/templates/catalog/proyectinstance_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Eleminar proyecto</h1>

<p>Seguro quieres eliminar esta inversión: {{ proyectinstance }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Sí" />
</form>

{% endblock %}

mexigrow/catalog/templates/catalog/proyectinstance_detail_owned_user.html
{% extends "base_generic.html" %}

{% block content %}
<script type="text/javascript">
    
  function display () {
    document.getElementById("myUl").innerHTML="";
    
    

    let time_rate = document.getElementById("rate-time").value;
    let tot = 1 * document.getElementById("investment").value;
    let interest = document.getElementById("interest").value;
    let time = document.getElementById("time").value;
    interest = interest/ 100;
    
    
    

    let li = document.createElement("li");
    let text = document.createTextNode("mes   /   saldo   /   ganancia mensual   /   ganancia acumulada");
    li.appendChild(text);
    document.getElementById("myUl").appendChild(li);
    

    let acc_gains_num = 0;
    let acc_gains_year = 0;
    let año=0;

    for (i = 0; i < time; i++) {
      if (i % time_rate == 0) {
        tot += acc_gains_num;
        acc_gains_num = 0;
      }
      
      if (i % 12 == 0) {
        let li = document.createElement("li");
        let text = document.createTextNode("ganacias " + (año+2022) + " " + (acc_gains_year));
        li.appendChild(text);
        document.getElementById("myUl").appendChild(li);
        año++;
        acc_gains_year = 0;
      }

      let monthly_gains_num = ((tot*interest)/360)*31;
      acc_gains_num += monthly_gains_num;
      acc_gains_year += monthly_gains_num;
      

      let li = document.createElement("li");
      let text = document.createTextNode((i+1) + "  -  " + tot + "  -  "+ monthly_gains_num + "  -  " + acc_gains_num);
      li.appendChild(text);
      document.getElementById("myUl").appendChild(li);
      
    }
    }
</script>

  
  <h1>Nombre del proyecto: {{ pi.proyect.title }}</h1>

  <p><strong>Compañía:</strong>{{ pi.proyect.company }}</p>
  <p><strong>Resumen del proyecto:</strong>{{ pi.proyect.summary }}</p>
  <p><strong>Día en que se publicó el proyecto:</strong>{{ pi.proyect.date_published }}</p>
  <p><strong>Tasa de interés:</strong>{{ pi.proyect.interest_rate }}</p> 
  
  <p><strong>Día en que me uní al proyecto:</strong>{{ pi.date_acquired }}</p>
  <p><strong>Día en finaliza mi participación en el proyecto:</strong>{{ pi.date_of_end_contract }}</p>

  <p><strong>Inversión:</strong>{{ pi.investment }}</p>


  <form name="Calculator">
    <table>
      <tr>
        <td>
          <label for="investment">Monto a invertir</label>
          <input type="number" name="tot" id="investment" value="{{ pi.investment }}" disabled>
        </td>
        <td>
          <label for="interest">Interés</label>
          <input type="number" name="interest" id="interest" value="{{ pi.proyect.interest_rate }}" disabled>
        </td>
        <td>
          <label for="time">Meses</label>
          <input type="number" name="time" id="time" value="0">
        </td>
        <td>
          <label for="time_rate">Tiempos para reinversión, si no hay reinversión sólo pon cero</label>
          <input type="number" name="rate_time" id="rate-time" value="{{ pi.rate_time }}" disabled>
        </td>
        <td>
          <button name="submit" type="button" onclick="display()"> Hello </button>
        </td>
        
      </tr>
    </table>
    <p id="myUl">
    </p>
  </form>

{% endblock %}

mexigrow/catalog/templates/catalog/proyectinstance_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

mexigrow/catalog/templates/catalog/proyectinstance_list_owned_user.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="mi">
    <div class="mi_left">
      <div class="mi_left_cnt">
    <h1>Mis inversiones</h1>

    {% if proyectinstance_list %}
    <ul>

      {% for proyectinst in proyectinstance_list %}
      <li class="{% if proyectinst.proyect_participation_ended %}text-danger{% endif %}">
        <h2><a href="{% url 'my-investment' proyectinst.id %}">{{proyectinst.proyect.title}}</a></h2> 
        <h3>Inversión: {{ proyectinst.investment }}</h3>
        <h3>Fecha de unión al proyecto: {{ proyectinst.date_acquired }}</h3>
        <h3>Fecha de termino de unión al proyecto: {{ proyectinst.date_of_end_contract }}</h3>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No tienes inversiones de momento.</p>
    {% endif %}
    </div>
    </div>
    <div class="mi_right">
      <div class="mi_right_cnt">
      <div class="messages">
        <h2>Mensajes</h2>
        <ul>
          <li class="li_1">
            <h3>Actualiza tu perfil</h3>
            <h4>Lorem ipsum dolor sit amet consectetur adipiscing elit conubia, enim porttitor nisi ultricies egestas magna litora faucibus aliquet.</h4>
          </li>
          <hr>
          <li>
            <h3>Proximo fin de mes</h3>
            <h4>Lorem ipsum dolor sit amet consectetur adipiscing elit conubia, enim porttitor nisi ultricies egestas magna litora faucibus aliquet.</h4>
          </li>
          <hr>
          <li>
            <h3>Crea una nueva inversión y aprovecha</h3>
            <h4>Lorem ipsum dolor sit amet consectetur adipiscing elit conubia, enim porttitor nisi ultricies egestas magna litora faucibus aliquet.</h4>
          </li>
        </ul>
      </div>
      <div class="documents">
        <h2>Mis documentos</h2>
        <div class="documents_cnt">
        <ul>
          <li class="li_1">
            <h3>Acta de nacimiento</h3>
          </li>
          
          <li>
            <h3>Facturas 2023-2024</h3>
          </li>
          
          <li>
            <h3>Acta de nacimiento</h3>
          </li>
        </ul>
      </div>
      </div>
    </div>
  </div>
  </div>

{% endblock %}